<a href="https://colab.research.google.com/github/vini1lol/Treinamento-simples-perceptron/blob/master/Treinamento_Perceptron_simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron 

Exercício simples para treinar um perceptron 

## Base 
Rede do tipo Perceptron formada por um neurônio com três terminais de entrada, utilizando pesos iniciais w0 = 0.7, w1 = -0.4 e w2 = 0.2, limiar θ = 0.5 e uma taxa de aprendizado = 0.5.

In [8]:
# Dados iniciais
import numpy as np 
# Base de dados
# Classe -1  
A = np.array( [0, 1, 0] ) 
# Classe 1 
B = np.array( [1, 1, 1] ) 
# Pesos iniciais 
Pesos = np.array( [0.7, -0.4, 0.2] ) 
# Taxa de aprendizagem 
eta = 0.5 
# Viés 
bias = 0.5  

In [9]:
# Função para a soma ponderada 
# m = x0*w0 +  x1*w1 + x2*w2+ x3*w3
# u = m -1*θ
def somaPonderada(X,W):
  bias = 0.5 
  m = np.multiply(X,W)
  u = np.sum(m) -1*bias
  return u 

In [10]:
# Função de ativação 
# Função Degrau 
def funcaoAtivacao(u):
  if u >= 0:
    return 1
  else:
    return -1

In [11]:
# Função de saída 
def saida(X,W):
  u = somaPonderada(X,W)
  return funcaoAtivacao(u) 


In [12]:
# Função para ajustes dos pesos
# Parte cententral do processo de aprendizagem 
# novo wi  →  wi = wi +  η xi (d - y ) 
def ajustaPesos(eta,W,X,bias,d,y):
  e = d - y 
  novoW = W + eta*X*e
  novoB = bias + eta*(-1)*e 
  return novoW, novoB  


# Treinamento 
* Realizado manualmente para ilustrar o processo 
* Aprsenta uma entrada e calcula a saída de maneira iterativa 

## Iteração 1

In [13]:
# Entrada 010 saída -1 
d = -1 
y = saida(A,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,A,bias,d,y) 
print(Pesos)
print(bias)  

# Entrada 111 saída +1
d = 1 
y = saida(B,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,B,bias,d,y) 
print(Pesos)
print(bias)

-1
[ 0.7 -0.4  0.2]
0.5
-1
[1.7 0.6 1.2]
-0.5


## Iteração 2

In [14]:
# Entrada 010 saída -1 
d = -1 
y = saida(A,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,A,bias,d,y) 
print(Pesos)
print(bias)  

# Entrada 111 saída +1
d = 1 
y = saida(B,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,B,bias,d,y) 
print(Pesos)
print(bias) 

1
[ 1.7 -0.4  1.2]
0.5
1
[ 1.7 -0.4  1.2]
0.5


## Iteração 3

In [17]:
# Entrada 010 saída -1 
d = -1 
y = saida(A,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,A,bias,d,y) 
print(Pesos)
print(bias)  

# Entrada 111 saída +1
d = 1 
y = saida(B,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,B,bias,d,y) 
print(Pesos)
print(bias) 

-1
[ 1.7 -0.4  1.2]
0.5
1
[ 1.7 -0.4  1.2]
0.5


# Teste
* A que classe pertencem os padrões 110, 000, 100 e 011

In [20]:
# Padrão 110
T = np.array([1, 1, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [1 1 0]  é  1


In [21]:
# Padrão 000 
T = np.array([0, 0, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [0 0 0]  é  -1


In [23]:
# Padrão 100 
T = np.array([1, 0, 0]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [1 0 0]  é  1


In [24]:
# Padrão 011
T = np.array([0, 1, 1]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [0 1 1]  é  1
